### ISSUE TITLE
createDataChannel 事件不触发

### ISSUE THREAD

**Issue by songguangyu** [PearInc/PearPlayer.js#10]
请问一下 createDataChannel 调用后 channel.onopen onmessage onerror onclose 都不触发 请问是什么原因呢？

**Comment by songguangyu** [comment]
看了一下 是 onicecandidate 在 setLocalDescription 后不能触发。

**Comment by snowinszu** [comment]
你是在哪个浏览器测试的？

**Comment by songguangyu** [comment]
chrome浏览器 
![image](https://user-images.githubusercontent.com/6869168/33641118-319ef868-da6f-11e7-8d49-4f99795bab9c.png)
这个是log 能帮看看哪个点出问题了吗？
