### ISSUE TITLE
看到只是播放器部分开源，如果内网使用会不会有安全问题？

### ISSUE THREAD

**Issue by codeskyblue** [PearInc/PearPlayer.js#2]

**Comment by liyongming1982** [comment]
获取cache节点列表的时候需要token才能返回，数据传输都是TLS/DTLS加密。

**Comment by codeskyblue** [comment]
其实我本来是打算在内网使用的，担心的是内部的视频资料会外泄

**Comment by Cheedoong** [comment]
@codeskyblue  不知您说的是由于JS播放器造成的视频资料外泄，还是由于终端（智能路由、NAS上的）程序造成的资料外泄？

**Comment by codeskyblue** [comment]
JS播放器呀

**Comment by Cheedoong** [comment]
@codeskyblue 不用担心，无论是终端程序还是JS，我们都不会索引和窃取用户数据的。

**Comment by liyongming1982** [comment]
@codeskyblue JS播放器的话，我们都是缓存在内存中喂给播放器，不会持久化视频文件。
